# Generated by Django 4.2.7 on 2025-04-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport_backend', '0003_alter_flight_airplane_alter_flight_route_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
