# Generated by Django 4.2.7 on 2025-05-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_backend', '0004_remove_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(related_name='flights_orders', to='airport_backend.crew'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('seat', 'row', 'flight'), name='unique_ticket_seat_row_flight'),
        ),
    ]
