# Generated by Django 4.2.7 on 2025-05-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport_backend', '0005_alter_flight_crew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='airplane_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplane_type', to='airport_backend.airplanetype'),
        ),
    ]
