# Generated by Django 4.2.7 on 2025-07-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport_backend', '0007_remove_ticket_unique_ticket_seat_row_flight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('row', 'seat')},
        ),
    ]
