# Generated by Django 4.2.7 on 2025-07-20 14:43

import airport_backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_backend', '0009_alter_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(null=True, upload_to=airport_backend.utils.create_custom_path_crew),
        ),
        migrations.AddField(
            model_name='crew',
            name='image',
            field=models.ImageField(null=True, upload_to=airport_backend.utils.create_custom_path_airplane),
        ),
    ]
