# Generated by Django 4.2.7 on 2025-08-01 16:59

import airport_backend.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport_backend', '0011_alter_airplane_image_alter_crew_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='airport',
            name='closest_big_city',
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(null=True, upload_to=airport_backend.utils.create_custom_path)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_country', to='airport_backend.country')),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='closes_big_city',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='airport_city', to='airport_backend.city'),
        ),
    ]
