# Generated by Django 4.2.7 on 2025-08-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport_backend', '0012_country_remove_airport_closest_big_city_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='closes_big_city',
            new_name='closest_big_city',
        ),
    ]
