# Generated by Django 4.2.7 on 2025-08-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_backend', '0013_rename_closes_big_city_airport_closest_big_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='flights_orders', to='airport_backend.crew'),
        ),
    ]
